# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 200707558272-te7t2gl0frolmfep3rolgc1l8k71drgb.apps.googleusercontent.com
            client-secret: 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
            redirectUri: {baseurl}/oauth2/callback/{registrationId}
            scope:
              - email
              - profile